services:
  client-reports:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client-reports
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - DATABASE_TYPE=sqlite
      - NEXT_PUBLIC_GIT_COMMIT_SHA=standalone
      - NEXT_PUBLIC_GIT_BRANCH=standalone 