name: Secrets Scanning

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Trufflehog
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sudo sh -s -- -b /usr/local/bin
      
      - name: Scan for secrets
        run: |
          trufflehog git file://. --since-commit HEAD~20 --fail
        continue-on-error: true

      - name: Scan recent commits
        run: |
          trufflehog git file://. --only-verified --fail
        continue-on-error: true
      
      - name: Check for environment variables in codebase
        run: |
          if grep -r --include="*.{js,ts,jsx,tsx}" --exclude-dir={node_modules,.next,dist,build} "process.env" .; then
            echo "WARNING: Direct use of process.env found. Consider using the env helper instead."
          fi 